/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.library_app;

/**
 *
 * @author wasu
 */
public class Main_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Main_GUI
     */
    public Main_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmain = new javax.swing.JButton();
        btnbookhist = new javax.swing.JButton();
        btnmain1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 200);
        flowLayout1.setAlignOnBaseline(true);
        getContentPane().setLayout(flowLayout1);

        btnmain.setText("Borrow/Return Book");
        btnmain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmainActionPerformed(evt);
            }
        });
        getContentPane().add(btnmain);

        btnbookhist.setText("See Book Loan History");
        btnbookhist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbookhistActionPerformed(evt);
            }
        });
        getContentPane().add(btnbookhist);

        btnmain1.setText("See Fine Report");
        btnmain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmain1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnmain1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmainActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Borrow_Return br = new Borrow_Return();
        br.setVisible(true);
    }//GEN-LAST:event_btnmainActionPerformed

    private void btnbookhistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbookhistActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Monthly_History_Loan hl = new Monthly_History_Loan();
        hl.setVisible(true);
    }//GEN-LAST:event_btnbookhistActionPerformed

    private void btnmain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmain1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Monthly_History_fine hf=new Monthly_History_fine();
        hf.setVisible(true);
    }//GEN-LAST:event_btnmain1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbookhist;
    private javax.swing.JButton btnmain;
    private javax.swing.JButton btnmain1;
    // End of variables declaration//GEN-END:variables
}
